name: "PHP CodeSniffer Validations"
on: [ push, pull_request ]
jobs:
  validate-code-style:
    name: PSR-12 Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install PHP_CodeSniffer composer package
        run: composer global require "squizlabs/php_codesniffer-*"

      - name: Validate PSR-12 Code Style
        run: ~/.composer/vendor/bin/phpcs